### Examine intersection between the loci for Jurgens and Zheng in hg38

In [1]:
import pandas as pd
import numpy as np

In [2]:
Jurgens_df = pd.read_csv("Jurgens_GWAS_hits_GRCh38.bed", delim_whitespace=True, header=None)
Jurgens_df.columns = ["chr", "start", "end", "rsID", "prioritized_gene", "total_score"]
Jurgens_df.head()

    chr     start       end        rsID prioritized_gene  total_score
0  chr1   2212668   2212668   rs2503715              SKI            2
1  chr1   6203732   6203732  rs11121483           RNF207            3
2  chr1  16012430  16012430   rs1763605            HSPB7            2
3  chr1  45544980  45544980    rs518365            MAST2            2
4  chr1  51327586  51327586  rs72694111           CDKN2C            1

In [3]:
Zheng_df = pd.read_csv("Zheng_GWAS_hits_GRCh38.bed", delim_whitespace=True, header=None)
Zheng_df.columns = ["chr", "start", "end", "rsID", "prioritized_gene", "total_score"]
Zheng_df.head()

    chr     start       end        rsID prioritized_gene  total_score
0  chr1   2212668   2212668   rs2503715          C1orf86            1
1  chr1   3324690   3324690  rs79548216           PRDM16            3
2  chr1   6218354   6218354    rs709209           RNF207            3
3  chr1  16013277  16013277   rs1763604            HSPB7            4
4  chr1  16018235  16018235    rs945418            HSPB7            4

In [4]:
intersecting_SNPs = list( set(Zheng_df.rsID) & set(Jurgens_df.rsID) )
print(f"Number of intersecting SNPs: {len(intersecting_SNPs)}")
intersecting_SNPs

Number of intersecting SNPs: 12

['rs3176326',
 'rs2540277',
 'rs4659701',
 'rs72840788',
 'rs6566955',
 'rs1400771',
 'rs205653',
 'rs2503715',
 'rs7835298',
 'rs72801474',
 'rs62222424',
 'rs242557']

In [5]:
Jurgens_df[Jurgens_df['rsID'].isin(intersecting_SNPs)]

      chr      start        end        rsID prioritized_gene  total_score
0    chr1    2212668    2212668   rs2503715              SKI            2
8    chr1  236689867  236689867   rs4659701            ACTN2            4
11   chr2  102809718  102809718   rs2540277          TMEM182            2
21   chr4   16033011   16033011   rs1400771            PROM1            4
26   chr5  133108436  133108436  rs72801474            HSPA4            5
29   chr6   36679512   36679512   rs3176326           CDKN1A            2
31   chr6   90502416   90502416    rs205653           MAP3K7            4
38   chr8  123540063  123540063   rs7835298           FBXO32            5
42  chr10  119656173  119656173  rs72840788             BAG3            5
55  chr17   45942346   45942346    rs242557             MAPT            4
59  chr18   58255557   58255557   rs6566955           NEDD4L            4
62  chr21   29157810   29157810  rs62222424            BACH1            2

In [6]:
Zheng_df[Zheng_df['rsID'].isin(intersecting_SNPs)]

       chr      start        end        rsID prioritized_gene  total_score
0     chr1    2212668    2212668   rs2503715          C1orf86            1
14    chr1  236689867  236689867   rs4659701            ACTN2            5
18    chr2  102809718  102809718   rs2540277          TMEM182            3
32    chr4   16033011   16033011   rs1400771            PROM1            3
39    chr5  133108436  133108436  rs72801474            HSPA4            3
41    chr6   36679512   36679512   rs3176326           CDKN1A            4
42    chr6   90502416   90502416    rs205653           MAP3K7            3
47    chr8  123540063  123540063   rs7835298           FBXO32            3
59   chr10  119656173  119656173  rs72840788             BAG3            5
85   chr17   45942346   45942346    rs242557             MAPT            3
91   chr18   58255557   58255557   rs6566955           NEDD4L            3
101  chr21   29157810   29157810  rs62222424            BACH1            2

### The two papers agree on the prioritized genes except for rs2503715, which Jurgens prioritizes SKI  (with relatively low priority score), while Zheng prioritizes C1orf86